- app/Http/Controllers/ApplicationController.php
- app/Http/Controllers/DashboardController.php
- app/Models/User.php
- resources/views/application/create.blade.php
- resources/views/components/justificativa-aluno.blade.php
- resources/views/cradt/index.blade.php
- resources/views/dashboard/index.blade.php
> Correção puxar dados pelo banco

- app/Http/Controllers/CradtController.php
- app/Http/Controllers/DashboardController.php
- database/seeders/ApplicationSeeder.php
- resources/views/components/justificativa-aluno.blade.php
- resources/views/cradt/index.blade.php
- resources/views/dashboard/index.blade.php
> Atualizando seeders, e paginação.

- app/Http/Controllers/CradtController.php
- database/seeders/DatabaseSeeder.php
- resources/views/components/justificativa.blade.php
- resources/views/cradt/index.blade.php
- routes/web.php
> Feat: Search with filter on CradtView

- resources/views/components/justificativa.blade.php
Este PR tem o intuito de adicionar estilização nas visualizações dos botões Finalizar e Indeferir, no qual quando selecionado um dos dois status os outros botões somem, deixando apenas o botão do PDF ativo.
```
justificativa.blade.php
```
Para testar a mudança basta apenas Finalizar ou Indeferir o Requerimento, Com isto já é possível notar a atualização.
> Lógica de visualização dos botões "Indeferir ou Finalizar" adicionadas

- app/Http/Controllers/ApplicationController.php
- database/migrations/2025_02_13_002741_add_motivo_to_requerimentos_table.php
- resources/views/components/justificativa-aluno.blade.php
- resources/views/components/justificativa.blade.php
- resources/views/cradt/index.blade.php
- resources/views/dashboard/index.blade.php
Atualização no botão indeferir, ao clicar no mesmo aparece um modal, pedindo o motivo do indeferimento
`justificativa.blade.php`
`justificativa-aluno.blade.php`
`index.blade.php (cradt)`
`index.blade.php (dashboard)`
adicionada uma migration para vincular motivo ao banco
`2025_02_13_002741_add_motivo_to_requerimentos_table.php`
Basta indeferir um requerimento que o modal aparecerá, e adicionando o motivo, ficará visível nos requerimentos indeferidos, tanto para aluno quanto Cradt.
> Modal do botão indeferir

- app/Http/Controllers/ApplicationController.php
- resources/views/application/edit.blade.php
- resources/views/components/justificativa-aluno.blade.php
- resources/views/components/justificativa.blade.php
- routes/web.php
Este commit adiciona a função de editar uma pendência dos requerimentos.
`justificativa-aluno.blade.php`
`justificativa.blade.php`
`web.php`
e criei o
`edit.blade.php`
Só basta na tela do ADM por o requerimento como pendente, e na tela do aluno apertar o botão corrigir e preencher os dados conforme necessário.
> Pending modal/logic for requerimento edit

- resources/views/components/justificativa.blade.php
Arrumado a rota do pdf que estava sempre puxando o primeiro ID.
`justificativa.blade.php`
> fix: Route PDF in justificativa.blade

- app/Http/Controllers/ProfileController.php
- package-lock.json
- resources/views/profile/edit.blade.php
Correção na edição de CPF, RG e matrícula no perfil do usuário, agora essas edições estão sendo salvas.
Único arquivo que talvez exija atenção `app\Http\Controllers\ProfileController.php`.
> Correção na edição de CPF, RG e matrícula no perfil do usuário

- resources/views/auth/login.blade.php
- resources/views/components/justificativa-aluno.blade.php
- resources/views/components/justificativa.blade.php
Arrumei a questão de visualização de anexos
> fix: view anexos routes

- app/Http/Controllers/ApplicationController.php
- resources/views/application/edit.blade.php
- resources/views/application/index.blade.php
Adicionada a possibilidade de inserir múltiplos anexos num requerimento.
> Refactor: Add many annex in Requerimento

- database/seeders/DatabaseSeeder.php
- resources/views/components/justificativa.blade.php
Arrumei erro de rota na parte da view da cradt
> fix: route for annex

- app/Http/Controllers/CradtController.php
- app/Http/Controllers/DashboardController.php
- app/Http/Controllers/EventController.php
- app/Models/Event.php
- database/migrations/2025_02_22_232927_create_events_table.php
- resources/views/cradt/index.blade.php
- resources/views/dashboard/index.blade.php
- routes/web.php
Adicionada tela de evento que marca atividades criadas pela cradt.
> Feat: Add event view

- app/Models/Event.php
- resources/views/components/justificativa.blade.php
Uma linha que não retornava os anexos quando inseridos mais de um
> fix: view annexs

- resources/views/cradt/index.blade.php
- resources/views/dashboard/index.blade.php
- resources/views/layouts/navigation.blade.php
Quando não houver eventos listados a aba de eventos não aparece
> feat: Ux/Ui update in Events Section

- database/seeders/DatabaseSeeder.php
- database/seeders/EventSeeder.php
- resources/views/cradt/index.blade.php
Novo seeder para o banco de dados e alteração no botão
`DatabaseSeeder.php`
`EventSeeder.php`
> New seeder for the database and changes to the button

- app/Models/Event.php
- database/migrations/2025_02_22_232927_create_events_table.php
Os eventos passam a ser excluídos 1 dia depois da sua data de Expiração.
> fix: auto delete/events

- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Controllers/CradtController.php
- database/migrations/2025_02_23_225453_modify_users_table_nullable_fields.php
- resources/views/layouts/navigation-cradt.blade.php
- routes/web.php
Agora, uma pessoa com o cargo "CRADT", consegue realizar um pré-cadastro para outro funcionário.
`CradtController.php`
`navigation-cradt.blade.php`
> feat: Possibility for an ADM to pre-register for another employee

- app/Http/Controllers/ApplicationController.php
- resources/views/application/edit.blade.php
- resources/views/auth/register.blade.php
o bug não permitia seleção de período maior que 6, e o campo de Curso.
`ApplicationController`
`application/edit.blade.php`
_Caso necessário, substitua esta …
> Fix bug na edição de um requerimento

- resources/views/cradt-report/index.blade.php
- resources/views/cradt/index.blade.php
- resources/views/dashboard/index.blade.php
Organizada a lógica dos gráficos + aviso ux no event card + exportar dados do grafico com CSV
_Caso necessário, substitua …
> Fix and Feat in Relatórios page and Event Card

- app/Http/Controllers/CradtReportController.php
- resources/views/cradt-report/index.blade.php
- resources/views/welcome.blade.php
- routes/web.php
Este PR visa corrigir lógica de busca de relatórios por data, e também corrigir erros de rotas provenientes do front-end.
`welcome.blade.php`
`CradtReportController.php`
`web.php`
_Caso necessário, substitua esta linha …
> fix: Chart date/ Routes redirect

- app/Http/Controllers/CradtReportController.php
- resources/views/cradt-report/index.blade.php
Arrumado questão de buscar relatórios anual.
`CradtReportController`
`cradt-report/index.blade.php`
> Fix: Filter by Year in charts/cradt

- public/css/style.css
- resources/views/application/index.blade.php
- resources/views/welcome.blade.php
-   [x] Optimization/Otimização
Apenas atualizações visuais
`index.blade.php`
> fix: ajustes na página de requerimento.

- resources/views/application/success.blade.php
Apenas uma modificação de visual
`secess.blade.php`
> fix: página de sucesso do requerimento

- app/Http/Controllers/ApplicationController.php
- database/migrations/2025_03_24_030109_add_finalizado_por_to_application_requests_table.php
- database/migrations/2025_03_24_033033_add_resposta_and_anexos_finalizacao_to_requerimentos_table.php
- resources/views/components/approve-modal.blade.php
- resources/views/components/deny-modal.blade.php
- resources/views/components/justificativa-aluno.blade.php
- resources/views/components/justificativa.blade.php
- resources/views/components/pendent-modal.blade.php
- resources/views/dashboard/index.blade.php
Atualização da página da cradt sobre ao finalizar enviar documentos ou texto caso necessário, e marcar tambem qual usuario (cradt) finalizou|pendencia|indeferiu o requerimento.
- `app/Http/Controllers/ApplicationController.php`
- `database/migrations/2025_03_24_030109_add_finali...`
- `database/migrations/2025_03_24_033033_add_respo...`
- `resources/views/components/approve-modal.blade.php`
- `resources/views/components/deny-modal.blade.php`
- `resources/views/components/justificativa-aluno.blade.php`
- …
> Features atualização da resposta cradt com texto ou anexos

- app/Http/Controllers/EventController.php
- app/Models/Event.php
- database/migrations/2025_02_22_232927_create_events_table.php
- resources/views/cradt/index.blade.php
- resources/views/dashboard/index.blade.php
Auto delete de evento expirado arrumado.
`migration(event)`
`Event.php`
`EventController.php`
> fix: auto delete events on the expired date

- app/Http/Controllers/ApplicationController.php
- app/Http/Controllers/CradtReportController.php
- app/Models/ApplicationRequest.php
- database/migrations/2025_01_27_032500_create_application_requests_table.php
- database/migrations/2025_03_24_232903_add_resolution_columns_to_requerimentos.php
- resources/views/cradt-report/index.blade.php
- routes/web.php
Adição de relatório de dados cruzados, troca do design para Tailwind
- `app/Http/Controllers/ApplicationController.php`
- `app/Http/Controllers/CradtReportController.php`
- `app/Models/ApplicationRequest.php`
- `resources/views/cradt-report/index.blade.php`
- `routes/web.php`
-   [ ] I need help …
> feat: tailwind no relatorio + filtro combinado de busca

- app/Http/Controllers/ApplicationController.php
- resources/views/application/edit.blade.php
_Implementação de multi anexos para o usuario que precisar editar/corrigir um requerimento, e implementação da logica de editar tambem as informações adicionais  que alguns requerimentos possuem._
`app\Http\Controllers\ApplicationController.php`
`resources\views\application\edit.blade.php`
-   [ ] I …
> Multianexo tsk22 tsk34

- composer.lock
- public/js/filterJustificativas.js
- resources/views/cradt/index.blade.php
- resources/views/dashboard/index.blade.php
Alteração na tela inicial da cradt para exibir apenas os requerimentos "em andamento"
Arquivo modificado: filterJustificativas.js
> exibir apenas requerimentos em andamento

- app/Http/Controllers/ApplicationController.php
- app/Http/Controllers/EventController.php
Essa modificação visa corrigir o bug, no qual quando um evento era criado com uma data superior a do dia atual, o evento permitia a criação do requerimento especifico.
`EventController.php`
Criar um evento com uma data …
> fix: Event data correção Created_at

- app/Http/Controllers/ApplicationController.php
- app/Http/Controllers/EventController.php
- app/Models/RequisitionTypeEvent.php
- database/migrations/2025_04_05_182745_requisition_type_events.php
- resources/views/components/event-add-exception.blade.php
- resources/views/components/event-add.blade.php
- resources/views/components/event-config.blade.php
- resources/views/components/event-edit.blade.php
- resources/views/cradt/index.blade.php
- routes/web.php
Gerenciamento de tipos de requerimento feito pelo user, e melhorias visuais nos modais de evento em geral.
`EventController.php`
`RequisitionTypeEvent.php`
`index.blade.php(cradt)` 
_Caso necessário, substitua esta …
> feat: Gerenciamento de Eventos

- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Controllers/CradtController.php
- app/Http/Controllers/DashboardController.php
- app/Models/User.php
- public/css/datepicker.css
- public/js/datepicker.js
- public/js/filterJustificativas.js
- resources/views/auth/register.blade.php
- resources/views/cradt/index.blade.php
- resources/views/dashboard/index.blade.php
Arrumado a questão dos filtros de busca no campo cradt e aluno, e adição de verificadores no formulário de registro de usuário.
`CradtController.php`
`DashboardController.php`
`datepicker.css`
`datepicker.js`
`filterJustificativas.js`
`index.blade.php`(cradt)
`index.blade.php`(aluno)
`RegisteredUserController.php`
`User.php`
`register.blade.php`
-   [ ] No, and this is why:/Não, e este é o motivo: _Substitua esta linha com …
> Filter Update and Exception Register

- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Controllers/UserManagementController.php
- resources/views/cradt-report/index.blade.php
- resources/views/layouts/navigation-cradt.blade.php
- resources/views/layouts/navigation.blade.php
- resources/views/users/edit.blade.php
- resources/views/users/index.blade.php
- routes/web.php
Arrumei a questão do pré-cadastro, e mudei a visualização do modal de pré-cadastro, implantada tela de visualização de usuários.
- `app/Http/Controllers/UserManagementController.php`
- `resources/views/layouts/navigation-cradt.blade.php`
- `resources/views/users/edit.blade.php`
- `resources/views/users/index.blade.php`
- `routes/web.php`
- `resources/views/cradt-report/index.blade.php`
- `resources/views/layouts/navigation.blade.php`
- `app/Http/Controllers/Auth/RegisteredUserController.php`
**Recomendamos que tenha feito ao …
> Modificações, e nova página de usuários

- app/Http/Controllers/CradtController.php
- app/Http/Controllers/CradtReportController.php
- app/Http/Controllers/UserManagementController.php
- app/Http/Kernel.php
- app/Http/Middleware/Authenticate.php
- app/Http/Middleware/CheckRole.php
- app/Http/Middleware/EncryptCookies.php
- app/Http/Middleware/PreventRequestsDuringMaintenance.php
- app/Http/Middleware/RedirectIfAuthenticated.php
- app/Http/Middleware/TrimStrings.php
- app/Http/Middleware/TrustHosts.php
- app/Http/Middleware/TrustProxies.php
- app/Http/Middleware/ValidateSignature.php
- app/Http/Middleware/VerifyCsrfToken.php
- bootstrap/app.php
- composer.lock
- package-lock.json
- resources/views/layouts/navigation-cradt.blade.php
- resources/views/layouts/navigation.blade.php
- routes/web.php
Este PR visa subir para a main a criação de um middleware que usa da lógica das policies para gerenciar o acesso de usuários Aluno e Cradt às rotas do projeto, garantindo respostas como a de código de status HTTP 403 (Forbidden). Além disso, foram adicionados arquivos estruturais pendentes e foram ajustados os visuais em alguns botões das navbar das dashboards. 
**Arquivos criados:**
app/Http/`Kernel.php`
app/Http/Middleware/`Authenticate.php`
app/Http/Middleware/`CheckRole.php`
app/Http/Middleware/`EncryptCookies.php` …
> Error responses for unauthorized access

- public/js/requerimentos-realtime.js
- resources/views/cradt/index.blade.php
- routes/web.php
Criada a lógica de auto-reload na página quando há atualização de estado do requerimento.
`web.php`
`index.blade.php(cradt)`
`requerimentos-realtime.js`
Entrar com 2 contas user CRADT, e atualizar um requerimento estando na tela inicial da cradt …
> Auto-Reload in CradtPage

- resources/views/components/justificativa-aluno.blade.php
- resources/views/components/justificativa.blade.php
- resources/views/cradt/index.blade.php
Atualização nos componentes de aluno e cradt
`justificativa.blade.php`
`justificativa-aluno.blade.php`
_Caso necessário, substitua esta linha para …
> refactor: Atualização no visual de aluno/cradt.

- app/Policies/UserPolicy.php
- database/seeders/ApplicationSeeder.php
- database/seeders/DatabaseSeeder.php
- resources/views/layouts/navigation.blade.php
- resources/views/users/edit.blade.php
- resources/views/users/index.blade.php
- routes/web.php
Adição de mais usuários fictícios no banco, adição do usuário manager e inserção de dados no usuário cradt e aluno. …
> Adição do usuário manager, alterações no usuário CRADT e inserção de mais dados fictícios no banco.

- app/Http/Controllers/CradtReportController.php
- resources/views/cradt-report/index.blade.php
- resources/views/cradt-report/user-pdf.blade.php
- routes/web.php
Este PR implementa a geração de um Relatório Individual para o usuário CRADT/MANAGER, reunindo informações com base em seus atendimentos e apresentando métricas correspondentes.
`web.php`
`CradtReportController.php`
- Cradt-report
`index.blade.php`
`user-pdf.blade.php`
-   [x] I need help …
> feat: generate individual PDF report

- database/seeders/DatabaseSeeder.php
- resources/views/application/index.blade.php
- resources/views/vendor/pagination/tailwind.blade.php
`vendor/tailwind.blade.php`
_Caso …
> fix: pagination and seeders

- app/Http/Controllers/ApplicationController.php
- database/migrations/2025_05_06_180055_add_visualizado_to_requerimentos_table.php
- public/js/requerimentoVisualizacao.js
- resources/views/components/justificativa.blade.php
- resources/views/cradt/index.blade.php
- routes/web.php
Mudança funcional na lógica de tags novo,antigo e muito antigo na página dashboard Cradt.
`requerimentoVisualizacao.js`
`web.php` …
> Tags update

- app/Mail/WelcomeStudentMail.php
- app/Models/User.php
- app/Notifications/ResetPasswordNotification.php
- resources/views/auth/forgot-password.blade.php
- resources/views/auth/reset-password.blade.php
- resources/views/emails/new-event.blade.php
- resources/views/emails/new-request.blade.php
- resources/views/emails/request-status-changed.blade.php
- resources/views/emails/reset-password.blade.php
- resources/views/emails/welcome-student.blade.php
- tests/Feature/Auth/PasswordResetTest.php
Esse PR visa atualizar o visual da redefinição de senha para os padrões do SRE. Sem grandes modificações na implementação padrão do framework.
app/Mail/
`WelcomeStudentMail.php`
app/Models/
`User.php`
app/Notifications/
`ResetPasswordNotification.php`
resources/views/auth/
`forgot-password.blade.php`
`reset-password.blade.php`
resources/views/emails/
`new-event.blade.php`
`new-request.blade.php`
`request-status-changed.blade.php`
`reset-password.blade.php`
`welcome-student.blade.php`
tests/Feature/Auth/ …
> Refactor: updating default settings for password recovery.

- app/Http/Controllers/CradtController.php
- app/Http/Controllers/DashboardController.php
- app/Http/Controllers/ProfileChangeRequestController.php
- app/Http/Controllers/ProfileController.php
- app/Models/ProfileChangeRequest.php
- database/migrations/2025_05_08_013423_profile_change_request.php
- resources/views/components/deny-modal.blade.php
- resources/views/cradt/index.blade.php
- resources/views/dashboard/index.blade.php
- resources/views/profile/edit.blade.php
- routes/web.php
Atualização em relação a dados Pessoais no qual passara por uma verificação dos usuários responsáveis, fazendo com que eles solicitem e só depois de aprovado os dados mudam.
- `app/Http/Controllers/ProfileController.php`
- `resources/views/components/deny-modal.blade.php`
- `resources/views/cradt/index.blade.php`
- `resources/views/dashboard/index.blade.php`
- `resources/views/profile/edit.blade.php`
- `routes/web.php`
-   [ ] No, …
> Solicitação de Alteração de Dados Pessoais

- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Controllers/UserManagementController.php
- app/Models/User.php
- config/app.php
- database/migrations/2025_02_06_201037_add_fields_to_users_table.php
- public/css/loading-spinner.css
- public/js/filterJustificativas.js
- public/js/form-loading.js
- resources/views/application/edit.blade.php
- resources/views/application/index.blade.php
- resources/views/auth/register.blade.php
- resources/views/components/approve-modal.blade.php
- resources/views/components/deny-modal.blade.php
- resources/views/components/event-add-exception.blade.php
- resources/views/components/event-add.blade.php
- resources/views/components/event-edit.blade.php
- resources/views/components/loading-spinner.blade.php
- resources/views/components/pendent-modal.blade.php
- resources/views/cradt/index.blade.php
- resources/views/dashboard/index.blade.php
- resources/views/layouts/app.blade.php
- resources/views/layouts/appcradt.blade.php
- resources/views/layouts/apphome.blade.php
- resources/views/profile/edit.blade.php
- resources/views/users/edit.blade.php
- resources/views/users/index.blade.php
Esse PR modifica a logica de matricula adicionando caso de possivel 2 matricula, e tela de loading.
- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Controllers/Auth/UserManagementController.php
- app/Http/Controllers/ProfileController.php
- app/Models/User.php
- config/app.php
- public/css/loading-spinner.css
- public/js/form-loading.js
- public/js/filterJustificativas.js
- resources/views/components/approve-modal.blade.php
- resources/views/components/deny-modal.blade.php
- …
> Adição de segunda matricula e Reload
